### ISSUE TITLE
StringIndexOutOfBoundsException on win OS

### ISSUE THREAD

**Issue by picpicpic** [carlspring/relocation-maven-plugin#1]
Hello,
I've got the following exception when trying your plugin on a win7 OS.

The problem is related to the replaceAll statement.
When using a win7 OS, field séparator is "\" and \ is an escaping.

Regards
Aldric

Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 1
        at java.lang.String.charAt(String.java:686)
        at java.util.regex.Matcher.appendReplacement(Matcher.java:703)
        at java.util.regex.Matcher.replaceAll(Matcher.java:813)
        at java.lang.String.replaceAll(String.java:2189)
        at org.carlspring.maven.relocation.AbstractRelocationMojo.getOriginalArtifactBasedir(AbstractRelocationMojo.java:132)
        at org.carlspring.maven.relocation.RelocateSingleMojo.relocate(RelocateSingleMojo.java:47)
        ... 22 more

**Comment by carlspring** [comment]
What's are the GAV of the artifact in question?

**Comment by picpicpic** [comment]
Ha, sorry I forgot some informations : 

The problem occurs when replacing dot charaters
I was relocating the following dependance from our maven repository : 
-DoriginalGAV=EXTERNALS.org.springframework:spring-orm:2.5.6 -DrelocationGAV=org.springframework:spring-orm:2.5.6

Regards
Aldric

**Comment by carlspring** [comment]
Hi Aldric,

Would you like to try out the latest code? 
Just clone it and build it locally and it should work.

Let me know if it fixes the problem for you.

Martin
